version: '3'

services:
  <%= conf.appNameKC %>.webpack-server:
    build:
      context: ..
      dockerfile: Dockerfile.dev
      args:
        NPM_TOKEN: $NPM_TOKEN_Garlictech
    volumes:
      - '../src:/app/src'
      - '../artifacts:/app/artifacts'
      - './hooks:/app/hooks'
      - '../angular.json:/app/angular.json'
    environment:
      - NODE_ENV
      - CI
      - PROJECT_CONFIG
    entrypoint: ['sh', '-c', '${DOCKER_CMD}']
    ports:
      - '8081:8081'
      - '8092:8092'
      - '7081:4000'
      - '8888:8888'
